#!/usr/bin/env ruby

require 'fileutils'

$THE_DIR = '/var/opt/vpnh'
$TCO_DIR = File.join($THE_DIR, 'co')
$VPNH_PATH = File.join($TCO_DIR, 'vpnh')
$VPNH_SERVICE_PATH = File.join($TCO_DIR, 'vpnh.service')

def ensure_dir(path)
  FileUtils.mkdir_p(path) unless(path)
end

def install_shellrc(filepath)
  unless File.exists?(filepath)
    puts "install_shellrc. no such file at #{filepath}"
    return false
  end
  new_line = "export PATH=$PATH:#{$TCO_DIR} #VPNH_INSTALL"
  already_installed = false
  File.open(filepath) do |f|
    f.each_line do |line|
      line = line.strip
      if line == new_line
        puts "install_shellrc. already installed. --SKIPPED"
        already_installed = true
        break
      end
    end
  end
  return true if already_installed
  puts "install_shellrc. appending to PATH within #{filepath}..."
  File.open(filepath, 'a') do |f|
    f.puts(new_line)
  end
  puts "--- done"
  return true
end

def package_install(name)
  puts "package_install. installing #{name} ..."
  system("apt-get install -y #{name}")
end

def package_ensure(name)
  if `which #{name}`.strip.size > 0
    puts "package_ensure. #{name} already installed"
    return true
  end
  package_install(name)
end

#--- MAIN

package_ensure('curl')
package_ensure('openvpn')

puts "$THE_DIR = #{$THE_DIR}"
puts "$TCO_DIR = #{$TCO_DIR}"

if File.exists?($VPNH_PATH)
  puts "found existing vpnh at #{$VPNH_PATH}"
  puts "stopping vpnh manually..."
  system("#{$VPNH_PATH} stop")
  puts "--done"
end

ensure_dir($THE_DIR)
if Dir.exist?($TCO_DIR)
  puts "removing old checkout dir: #{$TCO_DIR}"
  FileUtils.rm_rf($TCO_DIR)
  puts "--done"
end

puts "copying new checkout dir: #{$TCO_DIR}"
FileUtils.cp_r(File.join(__dir__, '.'), $TCO_DIR)
puts "--done"

if `which systemctl`.strip.size > 0
  puts "installing vpnh systemd service..."
  system("systemctl --force disable vpnh")
  system("systemctl --force enable #{$VPNH_SERVICE_PATH}")
  system("systemctl daemon-reload")
  puts "starting vpnh daemon..."
  system("systemctl start vpnh")
  puts "--done"
end

install_shellrc(File.join(ENV['HOME'], '.bashrc'))
install_shellrc(File.join(ENV['HOME'], '.zshrc'))

puts "--done. installation complete."
