#!/usr/bin/env ruby

require 'set'

def user_exists?(name)
  users = Set.new(IO.read('/etc/passwd').split("\n").map {|e| e.split(':')[0] })
  users.member?(name)
end

def make_vpnuser
  name = 'vpnuser'
  if user_exists?(name)
    puts "SKIPPED make_vpnuser. user already exists"
    return
  end
  `useradd -m #{name}`
end

def add_routing_table
  tables = Set.new
  path = '/etc/iproute2/rt_tables'
  f = File.open(path)
  f.each_line do |line|
    line = line.gsub(/#(.+)/, '')
    next if line =~ /^\s*$/
    fields = line.split(/\s+/)
    priority = fields[0]
    name = fields[1]
    tables << name
    puts "found table. name=#{name} priority=#{priority}"
  end
  f.close
  if tables.member?('vpntable')
    puts 'vpntable already exists'
    return 
  end
  open(path, 'a') do |f|
    f.puts "1\tvpntable"
  end
end

unless ARGV.size === 6
  puts 'expecting 6 arguments from openvpn'
  exit 1
end
vpni_name = ARGV[0]
vpni_addr = ARGV[3]
vpni_mask = ARGV[4]
vpni_dot1 = vpni_addr.gsub(/\.\d+$/, '.1')

puts "vpni_name=#{vpni_name}"
puts "vpni_addr=#{vpni_addr}"
puts "vpni_mask=#{vpni_mask}"
puts "vpni_dot1=#{vpni_dot1}"

make_vpnuser
add_routing_table
