#!/usr/bin/env ruby

require 'fileutils'
require 'logger'
require 'json'

require_relative 'Util'
require_relative 'VpnhMaster.rb'

#--- BEG. Helpers
def die_with_usage(msg=nil, ecode=1)
  puts "\n#{msg}\n---" if msg
  puts <<EOF
Usage: #{File.basename($0)} [command]

help                       Display this message.

setup                      Execute one-time setup.
status                     Display status.
connect <ovpn_name>        Connect to a known ovpn.
disconnect                 Disconnect.
reconnect                  Disconnect then Connect.

config                     Show current config file.
config get <key>           Get a config value.
config set <key> <val>     Set a config value.

auths                      Show all auths.
auths del <name>           Delete an auth.
auths add <name> <user> <pass>
                           Add an auth.

ovpns                      Show all known ovpn files.
ovpns flush                Delete all ovpn files.
ovpns del <name>           Delete ovpn file with name.
ovpns add <path>           Add a ovpn file.
ovpns add <name> <path>    Add a ovpn file with name.
ovpns add name=<name> auth=<auth> <path>
                           Add a ovpn file with name and auth.

version                    Display version
EOF
  exit ecode
end
#--- END. Helper

#--- MAIN
die_with_usage("only root can run vpnh") unless Util.ami_root?

command = ARGV.join(" ").chomp
unless command && command.size > 0 
  die_with_usage
end

if command =~ /^\-*h(elp)?$/i
  die_with_usage(nil, 0)
end

master = VpnhMaster.new

def config_show(master)
  puts JSON.pretty_generate(master.config.to_h)
  unless master.config.is_valid?
    puts "--- errors: "
    master.config.errors.each do |err|
      puts "* #{err}"
    end
  end
end

if command =~ /^\-*v(ersion)?/i
  version = master.version
  if version
    puts "Version: #{version.join('.')}"
  else
    puts "ERROR: failed to get version"
  end
elsif command == 'server'
  master.server.ignition
elsif command == 'setup'
  ok = master.setup
  puts "ok=#{ok}"
elsif command == 'connect'
  master.connect
elsif command =~ /^connect ([a-zA-Z0-9\.\-_]+)/
  name = $1
  puts "name=#{name}"
  master.connect(name)
elsif command == 'disconnect'
  master.disconnect
elsif command == 'reconnect'
  master.reconnect
elsif command == 'server daemon'
  # run the server as a daemon unless it is already running
  master.server_daemon_ensure
elsif command == 'server config update'
  master.client.config_update
elsif command == 'server shutdown' || command == 'server stop' || command == 'stop'
  puts 'telling the server to gracefully shutdown...'
  master.client.shutdown
  puts '--done'
elsif command == 'status'
  puts JSON.pretty_generate(master.status)
elsif command == 'server_running?'
  puts master.server_running?.to_json
elsif command =~ /^ovpn_(up|down)(.*)$/
  # called by /usr/sbin/openvpn when an interface has come-up/gone-down
  # we modify the ovpn config file such that this is called
  up_or_down = $1
  unless ['up', 'down'].member?(up_or_down)
    puts "ERROR. expecting up or down"
    exit(1)
  end
  args = $2.strip.split(/\s+/)
  puts "args=#{args}"
  unless args.size === 6
    die_with_usage('expecting 6 arguments from openvpn')
  end
  vpni_name = args[0]
  vpni_addr = args[3]
  vpni_mask = args[4]
  puts "vpni_name=#{vpni_name}"
  puts "vpni_addr=#{vpni_addr}"
  puts "vpni_mask=#{vpni_mask}"
  meth = "ovpn_#{up_or_down}".to_sym
  ret = master.public_send(meth, vpni_name, vpni_addr)
  exit (ret ? 0 : 1)
elsif command == 'get_default_iface'
  puts Util.get_default_iface
elsif command == 'get_routing_tables'
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command =~ /routing_table_add ([a-zA-Z0-9_]+)/
  puts Util.routing_table_add($1)
  puts "---"
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command =~ /routing_table_del ([a-zA-Z0-9_]+)/
  puts Util.routing_table_del($1)
  puts "---"
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command == 'get_all_ifaces'
  puts Util.get_all_ifaces.to_a.to_json
elsif command == 'get_all_users'
  puts Util.get_all_users.to_a.to_json
elsif command =~ /^user_exists\? (.+)/
  puts Util.user_exists?($1)
elsif command == 'config show' || command == 'config get' || command == 'config'
  config_show(master)
elsif command =~ /^config get (.+)/
  key = $1.strip
  puts master.config.get(key)
elsif command =~ /^config set ([a-zA-Z0-9\-\._]+) (.+)/
  key = $1
  val = $2
  if val == 'nil' || val == 'null'
    val = nil
  end
  puts master.config.set(key, val)
  master.client.config_update
  puts "---"
  config_show(master)
elsif command == 'config default'
  master.config.default!
elsif command == 'auths flush'
  master.auths.flush
  puts "OK. all auths removed"
elsif command =~ /^ovpns add name=([a-zA-Z0-9\.\-_]+) auth=([a-zA-Z0-9\.\-_]+) (\S+)$/
  name = $1
  auth = $2
  path = $3
  puts "name=#{name}"
  puts "auth=#{auth}"
  puts "path=#{path}"
  out = master.ovpns.add(
    path, 
    name: name,
    auth: auth,
  )
  unless out
    puts "ERROR: failed to add to ovpns"
  end
elsif command =~ /^ovpns add ([a-zA-Z0-9\.\-_]+) (\S+)$/
  name = $1
  path = $2
  puts "name=#{name}"
  puts "path=#{path}"
  name = master.ovpns.add(
    path, 
    name: name,
  )
  if name
    puts "name=#{name}"
  else
    puts "ERROR: failed to add to ovpns"
  end
elsif command =~ /^ovpns add (\S+)$/
  path = $1
  puts "path=#{path}"
  name = master.ovpns.add(path)
  if name
    puts "name=#{name}"
  else
    puts "ERROR: failed to add to ovpns"
  end
elsif command == 'ovpns flush'
  ok = master.ovpns.flush
  puts "ok=#{ok}"
elsif command =~ /^ovpns del (.+)$/
  name = $1
  puts "ovpns del. name=|#{name}|"
  ok = master.ovpns.del(name)
  puts "ok=#{ok}"
elsif command == 'ovpns all' || command == 'ovpns show' || command == 'ovpns'
  out = master.ovpns.all
  if out
    puts JSON.pretty_generate(out)
  else
    puts "ERROR: failed to fetch ovpns"
  end
elsif command =~ /^auths add ([a-zA-Z0-9\.\-_]+) ([^\s]+) (.+)$/
  name = $1
  user = $2
  pass = $3
  puts "name=#{name}"
  puts "user=#{user}"
  puts "pass=#{pass}"
  master.auths.add(user, pass, name)
elsif command =~ /^auths add ([^\s]+) (.+)$/
  user = $1
  pass = $2
  puts "user=#{user}"
  puts "pass=#{pass}"
  name = master.auths.add(user, pass)
  puts "name=#{name}"
elsif command == 'auths all' || command == 'auths show' || command == 'auths'
  out = master.auths.all()
  if out
    puts JSON.pretty_generate(out.to_h)
  else
    puts "ERROR: failed to fetch auths"
  end
elsif command =~ /^auths del (\w+)$/
  name = $1
  puts "auths del. name=|#{name}|"
  ok = master.auths.del(name)
  puts "ok=#{ok}"
elsif command =~ /^user_add (\w+)/
  puts Util.user_add($1)
elsif command =~ /x (\w+)/
  # for experimentation only
  out = master.client.public_send($1)
  p out if out
else
  die_with_usage
end
