#!/usr/bin/env ruby

require 'fileutils'
require 'logger'
require 'json'

require_relative 'Util'
require_relative 'VpnhMaster.rb'

#--- BEG. Globals
$logger = Logger.new(STDOUT)
#--- END. Globals

#--- BEG. Helpers
def die_with_usage(msg=nil, ecode=1)
  puts "Usage: vpnh [command]"
  puts "\n#{msg}" if msg
  exit ecode
end
#--- END. Helper

#--- MAIN
die_with_usage("only root can run vpnh") unless Util.ami_root?

command = ARGV.join(" ").chomp
unless command && command.size > 0 
  die_with_usage
end

if command == 'help' || command == 'h'
  die_with_usage(nil, 0)
end

master = VpnhMaster.new

def config_show(master)
  puts JSON.pretty_generate(master.config.to_h)
  unless master.config.is_valid?
    puts "--- errors: "
    master.config.errors.each do |err|
      puts "* #{err}"
    end
  end
end

if command == 'server'
  master.server.ignition
elsif command == 'server daemon'
  Util.daemonize do
    master.server.ignition
  end
elsif command == 'server shutdown' || command == 'server stop' || command == 'stop'
  puts 'stopping vpnh server...'
  master.client.shutdown
  puts 'stopping vpnh server... DONE'
elsif command == 'status'
  puts JSON.pretty_generate(master.client.status)
elsif command == 'running_server_pid'
  puts master.running_server_pid
elsif command =~ /^ovpnup(.*)$/
  args = $1.strip.split(/\s+/)
  puts "args=#{args}"
  unless args.size === 6
    die_with_usage('expecting 6 arguments from openvpn')
  end
  vpni_name = args[0]
  vpni_addr = args[3]
  vpni_mask = args[4]
  puts "vpni_name=#{vpni_name}"
  puts "vpni_addr=#{vpni_addr}"
  puts "vpni_mask=#{vpni_mask}"
elsif command == 'get_default_iface'
  puts Util.get_default_iface
elsif command == 'get_routing_tables'
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command =~ /routing_table_add ([a-zA-Z0-9_]+)/
  puts Util.routing_table_add($1)
  puts "---"
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command =~ /routing_table_del ([a-zA-Z0-9_]+)/
  puts Util.routing_table_del($1)
  puts "---"
  puts JSON.pretty_generate(Util.get_routing_tables)
elsif command == 'get_all_ifaces'
  puts Util.get_all_ifaces.to_a.to_json
elsif command == 'get_all_users'
  puts Util.get_all_users.to_a.to_json
elsif command =~ /^user_exists\? (.+)/
  puts Util.user_exists?($1)
elsif command == 'config show' || command == 'config get'
  config_show(master)
elsif command =~ /^config get (.+)/
  key = $1.strip
  puts master.config.get(key)
elsif command =~ /^config set ([a-zA-Z0-9\-\._]+) (.+)/
  key = $1
  val = $2
  if val == 'nil' || val == 'null'
    val = nil
  end
  puts master.config.set(key, val)
  puts "---"
  config_show(master)
elsif command =~ /^user_add (\w+)/
  puts Util.user_add($1)
elsif command =~ /x (\w+)/
  out = master.client.public_send($1)
  puts out if out
else
  die_with_usage
end
